num1<-matrix(c(1:25),nrow=5,ncol=5)
print(num1)
num2<-matrix(c(26:50),nrow=5,ncol=5)
print("addition")
print(num1+num2)
print("subtraction")
print(num1-num2)
print("multiplication")
print(num1*num2)
print("division")
print(num1/num2)
print("modulus")
print(num1%%num2)
print("matrix multpiication")
print(num1%*%num2)
print("matrices with different dimentions")
m1<-matrix(c(1:20),nrow=5,ncol=4)
print(m1)
m2<-matrix(c(21:40),nrow=4,ncol=5)
print(m2)
print("matrix multiplication")
print(m1%*%m2)
print("cross product")
print(crossprod(num1,num2))

