data(mtcars)
data(cars)
print("SUMMARY OF MTCARS")
print(summary(mtcars))
print("SUMMARY OF CARS")
print(summary(cars))
print("STRUCTURE OF MTCARS")
print(str(mtcars))
print("STRUCTURE OF CARS")
print(str(cars))
print("QUARTILE OF MTCARS")
print("mpg")
print(quantile(mtcars$mpg))
print("cyl")
print(quantile(mtcars$cyl))
print("disp")
print(quantile(mtcars$disp))
print("hp")
print(quantile(mtcars$hp))
print("drat")
print(quantile(mtcars$drat))
print("wt")
print(quantile(mtcars$wt))
print("qsec")
print(quantile(mtcars$qsec))
print("vs")
print(quantile(mtcars$vs))
print("am")
print(quantile(mtcars$am))
print("gear")
print(quantile(mtcars$gear))
print("QUARTILE OF CARS")
print("speed")
print(quantile(cars$speed))
print("dist")
print(quantile(cars$dist))
